### ISSUE TITLE
Post a Trade Page

### ISSUE THREAD

**Issue by hussu010** [tnbCrow/Frontend#7]
This is a form page that will let users input all the specifications that they want to create the trading post. Contains:
- Role (Buyer/ Seller)
- Transaction Type (Cryptocurrency, Fiat, Online Payment)
- Payment Method (Dependent on the transaction type. If crypto, will contain bitcoin, lite coin, or if Fiat, USD, AUD and if Online Payment, consists Paypal, Apple Pay, etc.
- Currency (Currency that they want to use)
- Exchange (Dropdown of exchanges and value of the coin in that exchange)
- Margin (what percentage do they want to differ from the exchange price)
- Rate (Will be calculated from exchange and margin, will not be editable)
- number of coins that they want to trade
- TOS (text field where the user will post the terms of the trade)
- Min Reputation (Integer field where the user will enter the minimum reputation of the user who can send the trade request)
- Broadcast Trade (Boolean field)
- Is Active (Boolean Field)

**Comment by olowudaniel1** [comment]
Please elaborate on these: (i) Exchange (ii) Margin (iii) Rate

**Comment by dhakal0kushal** [comment]
@olowudaniel1 the `exchange` field shows the name of the exchange and price of the coin in that exchange. `Margin` is a percentage field where the users will adjust their `Rate` of coins.

Eg: if the user selects Exchange: Binance-0.035, and puts Margin:10%, then the Rate will be 0.0385
